### ISSUE TITLE
Attempting to choose non-utf-8 text file on text preview widget on Windows crashes

### ISSUE THREAD

**Issue by WillAdams** [KennedyRichard/nodezator#1] opened 2022-06-18 13:45 UTC
Pretty much any attempt to interact w/ the file objects crashes.

on Windows 10:

 - launch Nodezator
 - File | New --- create "test.ndz" in the user directory
 - right-click | Useful encapsulations | read_text_file
 - click on the green text folder to select a path
 - select an existing file on the desktop ("C:\Users\willa\Desktop\tolkienbooks.txt")

app vanishes

Are there crash logs or anything which will help?

**Comment by KennedyRichard** [comment] 2022-06-18 14:08
Please, go to the location where nodezator is installed and inside the "nodezator" folder there should be a "logs" folder with the logs from your session.

**Comment by KennedyRichard** [comment] 2022-06-18 15:06
Please, also try, to update your installation using `pip install --upgrade nodezator` (in my machine it only works when called 02 times), or download from github again, if you didn't install). Then, try the same steps you made again. This time a dialog should appear instead of the app crashing.

If you locate the logs upload them here so I can take a look, please.

**Comment by WillAdams** [comment] 2022-06-18 21:40
Updating to 1.0.5 allows selecting a filepath on Windows. Thanks!

**Comment by KennedyRichard** [comment] 2022-06-18 21:45
Oh, really? That's great news! May I close this issue them?

**Comment by WillAdams** [comment] 2022-06-18 21:47
Actually, I'm getting an error:

![image](https://user-images.githubusercontent.com/3543154/174457914-187326f5-c809-4173-b3ec-a0e18fcc057d.png)

**Comment by KennedyRichard** [comment] 2022-06-18 22:00
I believe I get the problem now. The node is fine, it even has a field where you can specify the encoding. The problem is that the widget has to load the file in order to show you a preview and it does so using a 'utf-8' encoding. To solve this I guess I'll have to either analyse the file and then choose the appropriate encoding used to load it for the preview or just keep using the utf-8 encoding by use a more lenient loading method that ignore unicode errors (the pathlib.Path.read_text() method has a parameter to allow this if I'm not mistaken).

I'll look into this right away and upload a new patch.

**Comment by KennedyRichard** [comment] 2022-06-18 22:20
Ok, please, try updating your Nodezator version to 1.0.6 now, and repeat the steps that led to your original problem. See if no errors are raised anymore.

Also, if the text is previewed in the widget, click the preview and see if the file is displayed in the text viewer inside the app, some characters should probably not render well, but apart from that it should be fine.

**Comment by WillAdams** [comment] 2022-06-18 23:25
That worked!

I'd suggest making the encoding entry a pop-up, and having the program determine the valid options and only afford them.

**Comment by KennedyRichard** [comment] 2022-06-18 23:31
Yes, setting the errors parameter to ignore encoding errors was just a stopgap measure to prevent the app to crash on the users and allow them to keep working. I'll think of a better solution. and put this problem in my to-do list.

Since I believe the problem (crashing) was solved, if you don't mind I'll be closing this issue.

**Closed** 2022-06-18 23:31 UTC
